In [35]:
import numpy
ndarr1 = numpy.genfromtxt('D:\\workspace\\python\\AI\\02_科学计算库Numpy\\data\world_alcohol.txt', dtype=str, delimiter=',')
print(type(ndarr1), ndarr1, sep='\n', end='------\n')

ndarr2 = numpy.array([1, 2, 3])
ndarr3 = numpy.array([[1, 2, 3], [1, 2, 3]])

print(type(ndarr2), ndarr2, ndarr2.shape, sep='\n',end='------\n')
print(type(ndarr3), ndarr3, ndarr3.shape, sep='\n', end='------\n')


<class 'numpy.ndarray'>
[['Year' 'WHO region' 'Country' 'Beverage Types' 'Display Value']
 ['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ..., 
 ['1987' 'Africa' 'Malawi' 'Other' '0.75']
 ['1989' 'Americas' 'Bahamas' 'Wine' '1.5']
 ['1985' 'Africa' 'Malawi' 'Spirits' '0.31']]------
<class 'numpy.ndarray'>
[1 2 3]
(3,)------
<class 'numpy.ndarray'>
[[1 2 3]
 [1 2 3]]
(2, 3)------
